FROM node:12.16.1-buster-slim

WORKDIR /app

# add /app/node_modules/.bin/ to PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install

COPY . /app

EXPOSE 8080

CMD ["npm", "run", "serve"]
