version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app:z
    environment:
      - NODE_ENV=development
      - VUE_APP_DASHBOARD_SERVER_URL=http://0.0.0.0:8000
