FROM node:12.16.1-buster-slim

WORKDIR /app

# add /app/node_modules/.bin/ to PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm install --silent

COPY . /app

EXPOSE 8080

CMD ["npm", "run", "serve"]
