name: Build the Docker image on master branch
on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: deploy the docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: danvergara/dashboardserver
          tag_with_sha: true
